#!/bin/bash
### Job name
#PS -N PLYU_LES_
### Mail to user
#PBS -m ae
#PBS -k o
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:59:00
#PBS -j oe
##module load acml/4.4.0  2015/petsc/gcc-4.9.2/openmpi-1.5.5/hypre-2.8.0b/3.1-rebuild 

#source /home/plyu/env_VFSWIND.source
#echo $LD_LIBRARY_PATH > env_debuginfo 2>&1
cd /$PBS_O_WORKDIR
#pwd >dir_debuginfo 2>&1
cp start.in fort.11
mpirun --bind-to-core ./hos_les.exe > err1 2>&1
#/safl/software/aegean/openmpi/1.5.5/gcc/4.7.0-fix/bin/mpirun --bind-to-core ./vwis > err1
